### ISSUE TITLE
Missing field elm-version

### ISSUE THREAD

**Issue by mgold** [deadfoxygrandpa/Elm-Test#17]
Trying to update a library that depends on this one for 0.15. I'm getting an error:

````
$ elm-package install

Error: Unable to get elm-package.json for deadfoxygrandpa/Elm-Test 1.0.3
Missing field "elm-version", acceptable versions of the Elm Platform (e.g. "0.15.0 <= v < 0.16.0").
    Check out an example elm-package.json file here:
    <https://github.com/evancz/elm-html/blob/master/elm_dependencies.json>
````

Broken example link aside, please add `"elm-version": "0.15.0 <= v < 0.16.0"` to elm-package.json and bump the version.

**Comment by deadfoxygrandpa** [comment]
Sorry, I'm just getting back into everything after being away for a while.
Was this resolved?

**Comment by maxsnew** [comment]
Yeah this should be sorted out with the new release
