### ISSUE TITLE
Update/add elm 0.15 binaries in elm-travis-cache

### ISSUE THREAD

**Issue by chendrix** [deadfoxygrandpa/Elm-Test#21]
How difficult would it be to add/update the 0.15 binaries to elm-travis-cache?

Or, alternatively, are there setup instructions to be able to generate our own binaries that can be wget in a travis build?

**Comment by jvoigtlaender** [comment]
Seen the [npm elm installer](https://www.npmjs.com/package/elm)? This might be a way to pull in the binaries in a travis build. Alternatively, [the installer's repo](https://github.com/kevva/elm-bin) contains 0.15 binaries (in [the vendor directory](https://github.com/kevva/elm-bin/tree/master/vendor)) that you might be able to use.

**Comment by chendrix** [comment]
That worked quite nicely




On Travis it builds extremely quickly now.




You can see how I've used it in my [.travis.yml](https://github.com/chendrix/elm-rogue/blob/master/.travis.yml)

**Comment by chendrix** [comment]
That worked quite nicely

On Travis it builds extremely quickly now.

You can see how I've used it in my [.travis.yml](https://github.com/chendrix/elm-rogue/blob/master/.travis.yml)
