### ISSUE TITLE
README Instructions Out of Date

### ISSUE THREAD

**Issue by maxsnew** [deadfoxygrandpa/elm-test#8]
They still show automaton which is no longer a dependency along with elm-get.

It should all be updated once Elm 0.13 comes out I think.

**Comment by jmejias** [comment]
Hi, I been trying unsuccessfully to implement the readme examples and using the lastest version and run into this issue.

```Port Error:
No argument was given for the port named 'responses' with type:

    IO.Runner.Response

You need to provide an initial value!

Find out more about ports here <http://elm-lang.org/learn/Ports.elm>
/Users/johnny/Projects/Elm/access-admin/tmp/test.js:8163
				throw error;
				      ^
Error: Port Error:
No argument was given for the port named 'responses' with type:

    IO.Runner.Response

You need to provide an initial value!```

Any help is appreciated.

Thanks

**Comment by joefiorini** [comment]
@jmejias Solved this by using an older version of `elm-io.sh` that still uses `jsdom` and sends the default value to the port. Download the script I used from https://raw.githubusercontent.com/avh4/elm-spec/master/elm-io.sh and try again.

Good luck!

**Comment by jmejias** [comment]
@joefiorini  Thanks that did the trick

**Comment by deadfoxygrandpa** [comment]
The README is now up to date with the current version. Closing this older issue.
